import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { colors, space } from '../src/theme';
import { useDsh } from '../src/useDsh';

const iconFor = (kind: string): keyof typeof Ionicons.glyphMap => kind === 'approval' ? 'shield-checkmark' : kind === 'error' ? 'warning' : kind === 'message' ? 'chatbubble-ellipses' : kind === 'bridge' ? 'radio' : 'checkmark-circle';
const colorFor = (kind: string) => kind === 'approval' ? colors.amber : kind === 'error' ? colors.red : kind === 'message' ? colors.blue : kind === 'bridge' ? colors.muted : colors.cyan;
const relativeTime = (iso: string) => { const minutes = Math.max(0, Math.floor((Date.now() - new Date(iso).getTime()) / 60000)); return minutes < 1 ? 'now' : minutes < 60 ? `${minutes}m` : `${Math.floor(minutes / 60)}h`; };

export default function ActivityScreen() {
  const dsh = useDsh();
  const stateLabel = dsh.state.name.replaceAll('-', ' ');
  return <View style={styles.screen}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()} style={styles.back}><Ionicons name="chevron-back" size={23} color={colors.text} /></Pressable><View><Text style={styles.heading}>Activity</Text><Text style={styles.headerMeta}>CONTROL PLANE</Text></View><Pressable accessibilityLabel="Open settings" onPress={() => router.push('/settings')} style={styles.iconButton}><Ionicons name="settings-outline" size={19} color={colors.muted} /></Pressable></View>
    <ScrollView contentContainerStyle={styles.content}><View style={styles.status}><View style={[styles.statusIcon, { backgroundColor: dsh.connected ? colors.cyanDim : colors.surface }]}><Ionicons name={dsh.connected ? 'radio-outline' : 'pulse-outline'} size={18} color={dsh.connected ? colors.cyan : colors.amber} /></View><View style={styles.statusCopy}><Text style={styles.statusTitle}>{stateLabel}</Text><Text style={styles.statusText}>{dsh.bridge?.bridgeName ?? 'No workstation paired'}{dsh.lastBseq ? `  ·  cursor ${dsh.lastBseq}` : ''}</Text></View><Pressable onPress={() => void dsh.refresh()} accessibilityLabel="Refresh activity"><Ionicons name="refresh-outline" size={18} color={colors.muted} /></Pressable></View><Text style={styles.eyebrow}>EVENT STREAM</Text><Text style={styles.subheading}>{dsh.connected ? 'Bridge, harness, and session events in one place.' : 'Reconnect to resume the live event stream.'}</Text><View style={styles.timeline}>{dsh.activity.map((item, index) => { const color = colorFor(item.kind); return <View style={styles.item} key={item.id}><View style={styles.lineWrap}><View style={[styles.eventIcon, { backgroundColor: `${color}20` }]}><Ionicons name={iconFor(item.kind)} size={16} color={color} /></View>{index < dsh.activity.length - 1 && <View style={styles.line} />}</View><View style={styles.itemBody}><View style={styles.itemRow}><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.time}>{relativeTime(item.time)}</Text></View><Text style={styles.detail}>{item.detail}</Text></View></View>; })}</View>{dsh.activity.length === 0 && <View style={styles.empty}><Ionicons name="radio-outline" size={25} color={colors.faint} /><Text style={styles.emptyTitle}>No live events yet</Text><Text style={styles.emptyText}>Pair a workstation or open a session to see activity.</Text></View>}</ScrollView><View style={styles.tabs}><Pressable style={styles.tab} onPress={() => router.replace('/')}><Ionicons name="layers-outline" size={19} color={colors.muted} /><Text style={styles.tabLabel}>Sessions</Text></Pressable><Pressable style={styles.tabActive}><Ionicons name="pulse" size={19} color={colors.cyan} /><Text style={styles.tabLabelActive}>Activity</Text></Pressable></View></View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.canvas, paddingTop: 46 }, header: { height: 69, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: 'row', alignItems: 'center', gap: 9 }, back: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' }, heading: { color: colors.text, fontSize: 18, fontWeight: '700' }, headerMeta: { color: colors.cyan, fontSize: 9, fontWeight: '800', letterSpacing: 1.2, marginTop: 3 }, iconButton: { width: 36, height: 36, marginLeft: 'auto', alignItems: 'center', justifyContent: 'center' }, content: { padding: space.xl, paddingBottom: 100 }, status: { minHeight: 58, padding: 11, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 28 }, statusIcon: { width: 34, height: 34, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, statusCopy: { flex: 1, minWidth: 0 }, statusTitle: { color: colors.text, fontWeight: '700', fontSize: 13, textTransform: 'capitalize' }, statusText: { color: colors.muted, fontSize: 11, marginTop: 3 }, eyebrow: { color: colors.cyan, fontSize: 10, fontWeight: '800', letterSpacing: 1.2 }, subheading: { color: colors.muted, fontSize: 13, marginTop: 6, lineHeight: 19 }, timeline: { marginTop: 28 }, item: { flexDirection: 'row', minHeight: 76 }, lineWrap: { width: 35, alignItems: 'center' }, eventIcon: { width: 30, height: 30, borderRadius: 8, justifyContent: 'center', alignItems: 'center' }, line: { flex: 1, width: 1, backgroundColor: colors.border, marginVertical: 4 }, itemBody: { flex: 1, paddingLeft: 11, paddingBottom: 20 }, itemRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 }, itemTitle: { color: colors.text, fontWeight: '600', fontSize: 13, flex: 1 }, time: { color: colors.faint, fontSize: 10 }, detail: { color: colors.muted, fontSize: 12, marginTop: 5, lineHeight: 17 }, empty: { alignItems: 'center', marginTop: 38 }, emptyTitle: { color: colors.text, fontSize: 14, fontWeight: '700', marginTop: 12 }, emptyText: { color: colors.muted, fontSize: 12, marginTop: 5, textAlign: 'center' }, tabs: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 66, backgroundColor: colors.surface, borderTopWidth: 1, borderTopColor: colors.border, flexDirection: 'row', justifyContent: 'space-around', paddingTop: 10 }, tab: { alignItems: 'center', gap: 3, width: 100 }, tabActive: { alignItems: 'center', gap: 3, width: 100 }, tabLabel: { color: colors.muted, fontSize: 11 }, tabLabelActive: { color: colors.cyan, fontSize: 11, fontWeight: '700' } });
